<?php

/**
 * Auto generated - any changes might be lost
 */

namespace Maslosoft\Sprite\Icon;

/**
 * Constants for sprite icons.
 * Generated by Maslosoft Sprite
 * 
 * @link http://maslosoft.com/sprite/
 */
class I
{

	const GroupKey = 'icon-16-group-key';
	const Group = 'icon-16-group';
	const Help = 'icon-16-help';
	const Key = 'icon-16-key';
	const NodeTree = 'icon-16-node-tree';
	const Recycle = 'icon-16-recycle';
	const TextListNumbers = 'icon-16-text-list-numbers';
	const ApplicationBlock = 'icon-16-application-block';
	const ApplicationViewColumns = 'icon-16-application-view-columns';
	const ApplicationViewDetail = 'icon-16-application-view-detail';
	const ApplicationViewGallery = 'icon-16-application-view-gallery';
	const ApplicationViewIcons = 'icon-16-application-view-icons';
	const ApplicationViewList = 'icon-16-application-view-list';
	const ApplicationViewTile = 'icon-16-application-view-tile';
	const Bin = 'icon-16-bin';
	const Block = 'icon-16-block';
	const CalendarViewDay = 'icon-16-calendar-view-day';
	const CalendarViewMonth = 'icon-16-calendar-view-month';
	const CalendarViewWeek = 'icon-16-calendar-view-week';
	const Cancel = 'icon-16-cancel';
	const Database = 'icon-16-database';
	const DiskBlack = 'icon-16-disk-black';
	const DocumentCopy = 'icon-16-document-copy';
	const DocumentText = 'icon-16-document-text';
	const Document = 'icon-16-document';
	const DriveUpload = 'icon-16-drive-upload';
	const Exclamation = 'icon-16-exclamation';
	const Flags = 'icon-16-flags';
	const FolderOpenDocumentText = 'icon-16-folder-open-document-text';
	const FolderOpenImage = 'icon-16-folder-open-image';
	const FolderOpenMixed = 'icon-16-folder-open-mixed';
	const Folder = 'icon-16-folder';
	const FolderAdd = 'icon-16-folder-add';
	const Gear = 'icon-16-gear';
	const GlobeGreenFlags = 'icon-16-globe-green-flags';
	const I18n = 'icon-16-i18n';
	const I18n2 = 'icon-16-i18n2';
	const ImportToDb = 'icon-16-import-to-db';
	const LightBulb = 'icon-16-light-bulb';
	const NewspaperPencil = 'icon-16-newspaper-pencil';
	const Newspaper = 'icon-16-newspaper';
	const NodeAffectChild = 'icon-16-node-affect-child';
	const NodeSelect = 'icon-16-node-select';
	const SortAlphabetDescending = 'icon-16-sort-alphabet-descending';
	const SortAlphabet = 'icon-16-sort-alphabet';
	const SortDateDescending = 'icon-16-sort-date-descending';
	const SortDate = 'icon-16-sort-date';
	const SortNumberDescending = 'icon-16-sort-number-descending';
	const SortNumber = 'icon-16-sort-number';
	const UiLayoutPanel = 'icon-16-ui-layout-panel';
	const UserPencil = 'icon-16-user-pencil';
	const UserImage = 'icon-16-user-image';
	const User = 'icon-16-user';
	const WorldDis = 'icon-16-world-dis';
	const World = 'icon-16-world';
	const WorldEdit = 'icon-16-world-edit';
	const EditorApplicationBlockAdd = 'icon-16-editor-application-block-add';
	const EditorApplicationBlockGear = 'icon-16-editor-application-block-gear';
	const EditorDocumentTask = 'icon-16-editor-document-task';
	const EditorDocumentUpdate = 'icon-16-editor-document-update';
	const EditorEditAlignmentCenter = 'icon-16-editor-edit-alignment-center';
	const EditorEditAlignmentJustify = 'icon-16-editor-edit-alignment-justify';
	const EditorEditAlignmentRight = 'icon-16-editor-edit-alignment-right';
	const EditorEditAlignment = 'icon-16-editor-edit-alignment';
	const EditorEditBold = 'icon-16-editor-edit-bold';
	const EditorEditHeading = 'icon-16-editor-edit-heading';
	const EditorEditImageCenter = 'icon-16-editor-edit-image-center';
	const EditorEditImageDefault = 'icon-16-editor-edit-image-default';
	const EditorEditImageRight = 'icon-16-editor-edit-image-right';
	const EditorEditImage = 'icon-16-editor-edit-image';
	const EditorEditIndent = 'icon-16-editor-edit-indent';
	const EditorEditItalic = 'icon-16-editor-edit-italic';
	const EditorEditListOrder = 'icon-16-editor-edit-list-order';
	const EditorEditList = 'icon-16-editor-edit-list';
	const EditorEditOutdent = 'icon-16-editor-edit-outdent';
	const EditorEditRule = 'icon-16-editor-edit-rule';
	const EditorEditShadow = 'icon-16-editor-edit-shadow';
	const EditorEditSizeDown = 'icon-16-editor-edit-size-down';
	const EditorEditSize = 'icon-16-editor-edit-size';
	const EditorEditSmall = 'icon-16-editor-edit-small';
	const EditorEditStrike = 'icon-16-editor-edit-strike';
	const EditorEditStyle = 'icon-16-editor-edit-style';
	const EditorEditSubscript = 'icon-16-editor-edit-subscript';
	const EditorEditSuperscript = 'icon-16-editor-edit-superscript';
	const EditorEditSymbol = 'icon-16-editor-edit-symbol';
	const EditorEditUnderline = 'icon-16-editor-edit-underline';
	const EditorEraser = 'icon-16-editor-eraser';
	const EditorFilmPlus = 'icon-16-editor-film-plus';
	const EditorFilmUpload = 'icon-16-editor-film-upload';
	const EditorFolderOpenGuideBlocks = 'icon-16-editor-folder-open-guide-blocks';
	const EditorGlobePlus = 'icon-16-editor-globe-plus';
	const EditorGlobeGreenMinus = 'icon-16-editor-globe-green-minus';
	const EditorGlobeGreenPencil = 'icon-16-editor-globe-green-pencil';
	const EditorGuideBlocksEdit = 'icon-16-editor-guide-blocks-edit';
	const EditorGuideBlocks = 'icon-16-editor-guide-blocks';
	const EditorGuide = 'icon-16-editor-guide';
	const EditorImageEdit = 'icon-16-editor-image-edit';
	const EditorImagePlus = 'icon-16-editor-image-plus';
	const EditorImageBackground = 'icon-16-editor-image-background';
	const EditorImageResizeActual = 'icon-16-editor-image-resize-actual';
	const EditorImageUpload = 'icon-16-editor-image-upload';
	const EditorPicturePencil = 'icon-16-editor-picture-pencil';
	const EditorSelectionInputHighlight = 'icon-16-editor-selection-input-highlight';
	const EditorSelectionInput = 'icon-16-editor-selection-input';
	const EditorSelectionResizeActual = 'icon-16-editor-selection-resize-actual';
	const EditorSlideAddAfter = 'icon-16-editor-slide-add-after';
	const EditorSlideAddBefore = 'icon-16-editor-slide-add-before';
	const EditorTableMinus = 'icon-16-editor-table-minus';
	const EditorTablePencil = 'icon-16-editor-table-pencil';
	const EditorTablePlus = 'icon-16-editor-table-plus';
	const EditorTableClear = 'icon-16-editor-table-clear';
	const EditorTableDeleteColumn = 'icon-16-editor-table-delete-column';
	const EditorTableDeleteRow = 'icon-16-editor-table-delete-row';
	const EditorTableInsertColumnLeft = 'icon-16-editor-table-insert-column-left';
	const EditorTableInsertColumnRight = 'icon-16-editor-table-insert-column-right';
	const EditorTableInsertColumn = 'icon-16-editor-table-insert-column';
	const EditorTableInsertHeader = 'icon-16-editor-table-insert-header';
	const EditorTableInsertRowAbove = 'icon-16-editor-table-insert-row-above';
	const EditorTableInsertRowBelow = 'icon-16-editor-table-insert-row-below';
	const EditorTableInsertRowInside = 'icon-16-editor-table-insert-row-inside';
	const EditorTableInsertRowSelectedAbove = 'icon-16-editor-table-insert-row-selected-above';
	const EditorTableInsertRowSelectedBelow = 'icon-16-editor-table-insert-row-selected-below';
	const EditorTableInsertRow = 'icon-16-editor-table-insert-row';
	const EditorTablePaintCan = 'icon-16-editor-table-paint-can';
	const EditorTable = 'icon-16-editor-table';
	const EditorUiPanelEraser = 'icon-16-editor-ui-panel-eraser';
	const EditorUiPanel = 'icon-16-editor-ui-panel';
	const DialogInformation = 'icon-32-dialog-information';
	const DialogWarning = 'icon-32-dialog-warning';
	const FaceDevilish = 'icon-32-face-devilish';
	const FaceGrin = 'icon-32-face-grin';
	const FacePlain = 'icon-32-face-plain';
	const FaceSmile = 'icon-32-face-smile';
	const SoftwareUpdateUrgent = 'icon-32-software-update-urgent';
	const TrashcanFull = 'icon-64-trashcan-full';

}
