<?php

/**
 * Auto generated - any changes might be lost
 * @generated
 */

namespace Maslosoft\Sprite\Icon;

/**
 * Constants for sprite icons.
 * Generated by Maslosoft Sprite
 * 
 * @link http://maslosoft.com/sprite/
 */
class I4
{

	const Amazon = 'icon-amazon';
	const Android = 'icon-android';
	const Behance = 'icon-behance';
	const Digg = 'icon-digg';

}
