<?php

/**
 * Auto generated - any changes might be lost
 */

namespace Maslosoft\Sprite\Icon;

/**
 * Constants for sprite icons.
 * Generated by Maslosoft Sprite
 * 
 * @link http://maslosoft.com/sprite/
 */
class I5
{

	const BlurredLogo60x100 = 'icon-blurred-logo-60x100';

}
